### ISSUE TITLE
Why this is happening

### ISSUE THREAD

**Issue by RianCaio** [julesontheroad/NSC_BUILDER#109]
https://youtu.be/hUdNTUCw9rs

**Comment by RianCaio** [comment]
This make imposible to drag any file or select any opcion

**Comment by deadair3210** [comment]
Making the video public would probably be a good first step.....

**Comment by RianCaio** [comment]
ok

**Comment by julesontheroad** [comment]
The other time i saw this it was someone that had that issue with the x64 build, it worked for him with the x86 one even if his system was a 64bits one. I don't know the reason.

**Comment by RianCaio** [comment]
well i tried the x86 one but when i gone merge game update it simply gave a unknown.xci with 68kb

**Comment by julesontheroad** [comment]
That's lack of the keys that are needed it gives you an error and stops when it can't decode the nca headers, since the xci header is written first the files ends as 68kb in your case. When the control nca file can't be read to set the name for a game it names it as unknown, that happens when you lack the keys or when the control nca is bad. Anyway in your case is clear you're lacking some of the keys from the template.
