### ISSUE TITLE
invalid Masterkey,ticket format and list index issues

### ISSUE THREAD

**Issue by pcwizard7** [julesontheroad/NSC_BUILDER#117]
i ve force update nut and verify keys

I m getting invalid ticket format on few files 
and one more invalid for masterkey set
also new error "list index out of range"

let me know what they mean and if it can be fixed?

thanks

**Comment by ItsCinnabar** [comment]
Give the titleid of the file and the error you are getting on it.

**Comment by pcwizard7** [comment]
Running file verify each file for the new dlc, and they all check out except it couldn't verify the ticket, error can't verify ticket format" even tho I could create a custom xci with them. So u may need to update them

here are the dlc in question

> Xenoblade Chronicles 2 v0 (0100E95004039006) (DLC)
Xenoblade Chronicles 2 v131072 (0100E95004039001) (DLC)
Xenoblade Chronicles 2 v196608 (0100E95004039004) (DLC)
Xenoblade Chronicles 2 v327680 (0100E95004039002) (DLC)
Xenoblade Chronicles 2 v327680 (0100E95004039003) (DLC)
Xenoblade Chronicles 2 v720896 (0100E95004039005) (DLC)

**Comment by ItsCinnabar** [comment]
I ran a verify on the first DLC you gave 0100E95004039006.

Decryption VERDICT: NSP FILE IS CORRECT
Signature 1 VERDICT: NSP  FILE IS SAFE
Hash VERDICT: NSP FILE IS CORRECT

Out of date NSCB? Missing some of the needed keys? Or possibly, redump the game from your switch because it may have gone wrong last time.

**Comment by pcwizard7** [comment]
The files was ok but the ticket couldn't be verified. And keys are valid

**Comment by julesontheroad** [comment]
The multimode doesn't have the ticket verification. I imagine the error is related to trying to support the nxdumptool format while keeping support for the old cdnsp tickets that had cryptotype2 in the wrong offset. I guess it only affects keygeneration2 files since that is a little different from the other keygenerations, i'll fix it in the next iteration of the program but i'm currently changing several stuff here and there so don't expect anything before next week.
That change was introduced in https://github.com/julesontheroad/NSC_BUILDER/releases/tag/v0.96d
So i'm pretty sure older versions will work fine with xenoblade in individual mode.

**Comment by julesontheroad** [comment]
@pcwizard7 i don't see to be having issues with them. I'll need these 2 things:
1.- Tell me exactly what function are you using
2.- Get me the txt files for **"FILE LIST of the xci\nsp"** if the tickets end by 2 are named incorrectly, keygeneration 2 is weird in that cryptotype 2=0 and the ticket should end by 0 too, as well as the cryptotype2 in the ticket should be 0. That's what will match the ncaheader.
Anyway i can delete the check and replace it for a keycheck like the one the verification has or something like that.

For example here's the data of the proper dump of Torna DLC:
![torna 2](https://user-images.githubusercontent.com/42461174/76167835-fe0dd080-6169-11ea-9f48-4f85460758ee.PNG)
![torna 1](https://user-images.githubusercontent.com/42461174/76167836-fea66700-6169-11ea-9947-3fffef865579.PNG)
As you can see keygeneration is 2 but the ticket ends by 0. 
When you check nut info you'll see how masterkeyrev=0, that's because in keygeneration 2 the cryptotype2=0 and cryptotype1=2. If the ticket is written incorrectly you'll see a missmatch, i saw some dumps of Torna with that written incorrectly. Again not an issue in the system, while improper and fixable by just issuing a warning instead of an exception, for example. I guess.
Still it doesn't seem to be the issue i first thought it was.
Nut info:
![torna 3](https://user-images.githubusercontent.com/42461174/76167937-c05d7780-616a-11ea-9048-b3f8cd4869a5.PNG)

**Comment by pcwizard7** [comment]
[Xenoblade Chronicles 2 [0100E95004038000] [v917504] (1G+1U+6D)-info.txt](https://github.com/julesontheroad/NSC_BUILDER/files/4312062/Xenoblade.Chronicles.2.0100E95004038000.v917504.1G%2B1U%2B6D.-info.txt)
[Xenoblade Chronicles 2 [0100E95004038000] [v917504] (1G+1U+6D)-Fcontent.txt](https://github.com/julesontheroad/NSC_BUILDER/files/4312063/Xenoblade.Chronicles.2.0100E95004038000.v917504.1G%2B1U%2B6D.-Fcontent.txt)

I d have to split the back into parts again which i ll do if you ask for it but here is file and nut infor files of the custom xci

**Comment by julesontheroad** [comment]
Yeah, I'm pretty sure the core issue there is that the original ticket was written incorrectly, most functions will work anyway since they were written to ignore that fact but individual modes make that check, or at least part of them.
Restore mode will restore back the tickets after splitting the file but will generate a new one from scratch so it won't have that issue, so only way to know for sure would be to see the original ticket.

**Comment by pcwizard7** [comment]
@julesontheroad you still around I hope you're ok

**Comment by julesontheroad** [comment]
I'm fine just little busy later, I updated the beta but it may be some time till i finsih my intended changes since i'm busy with work, it also adds some stuff like no console interface that will need to be build in a specific way on pyinstaller, probably so it'll have to wait till i have more time to debug stuff.
If someone needs an updated version he'll need to go with the beta on python for now. At least till i have time again to catch up with stuff.

**Comment by julesontheroad** [comment]
BTW i think this issue and the latest one while being diferent have the same core reason.

**Comment by pcwizard7** [comment]
Good to hear from you man we hadn't seen any activity from you for month ppl thought something happened to you lik4 covid or something.

there's also the issue with the mismatch masterkey error in "option 1 individual process"  and issue with nxdumptool dump combine issue in other ticket which u can discuss with me and creator od nxdumptool
