### ISSUE TITLE
The Legend of Zelda Breath of the Wild Dlc cannot  be repacked

### ISSUE THREAD

**Issue by seventeeeen** [julesontheroad/NSC_BUILDER#12]
The Legend of Zelda Breath of the Wild (rev002) WLD[01007EF00011E000][v1.5.0]
[DLC] The Legend of Zelda Breath of the Wild [01007ef00011f001][v196608]
[DLC] The Legend of Zelda Breath of the Wild [01007ef00011f002][v196608]
Dlc cannot  be repacked，only base and update can  be repacked

**Comment by julesontheroad** [comment]
It can, I have mine with DLCs + Updates. I use:
Update: The Legend of Zelda Breath of the Wild [01007ef00011e800][v720896].nsp
DLC1: [DLC] The Legend of Zelda Breath of the Wild DLC Pack 2 [01007ef00011f002][v196608]
DLC2: [DLC] Zelda BoW [01007ef00011f001][v196608].nsp
As base you need to use rev0 xci or the nsp.
**Your issue is that you're using rev2 that already has an update so your xci ends with 2 updates. Those will be supported as soon as I make "update mode" or split mode.**
Update mode will let you update games that already include games or dlc.
Split mode will let you split back the content. My split function is almost ready so the split mode will probably come this weekend, for update mode it'll depend on my time trough the weekend

**Comment by julesontheroad** [comment]
So to recapitulate you need to use the game as nsp or to use The.Legend.of.Zelda.Breath.of.the.Wild (rev 0) to repack the game. 8Equivalent to first zelda released by Big Blue Box)
For the xci the exact data is here http://nswdb.com/

**Comment by seventeeeen** [comment]
thank you

**Comment by julesontheroad** [comment]
As of now current master includes update mode for this cases and info mode to check files before doing processes with them.

**Comment by yangliu1317** [comment]
thank you
