### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Virallata** [julesontheroad/NSC_BUILDER#121]
Hello, when i do any command, i get the error:
py is not recognized as an internal or external command

**Comment by 7h3Cub3** [comment]
@Virallata it's because you downloaded the version NSCB_098bpy.zip instead of NSCB_098bx64.zip, the first is smaller in size but doesn't contain the whole python stack thus if you don't have python installed on your system, it's going to reply you are missing python. If you want it to work use the 2nd one in 32 or 64 bit flavor depending on your system and all will work. Cheers.

**Comment by julesontheroad** [comment]
Probably that though for python version if your system doesn't recognize py it can be changed in the config file for "python", "conda" or the python function the system recognizes.
