### ISSUE TITLE
Exception: No module named 'win32com'

### ISSUE THREAD

**Issue by justtryingthingsout** [julesontheroad/NSC_BUILDER#122]
in the python version that (should) support macOS, I'm getting the error `Exception: No module named 'win32com'`. I traced this back to line 311 and 312, which are 
```python
else:
	vret=secondary.call_library(args.library_call)
```
Please fix this, thank you! pywin32 and pypiwin32 is no longer supported on the latest python releases

**Comment by julesontheroad** [comment]
In case i made some change try with the current beta since i'm using it fine on Linux. The secondary library is used to mount dinamically libraries from other functions, these are not load at program boot and allow to not install all dependencies depending on the function used.
Linux and Mac won't need pywin32 and windows-curses. Pywin32 is used to set the archive flag on split nsps while windows-curses is not needed in linux which have acces to normal curses, dunno about mac.
Well first try the beta and if it doesn't work tell what function are you using. The core of the issue will be in the function the secondary module is trying to load dinamically.
