### ISSUE TITLE
Not technically a issue, more of a inquiry

### ISSUE THREAD

**Issue by Masamune3210** [julesontheroad/NSC_BUILDER#135]
Is there anywhere by chance that documents the differences between a multicontent nsp and a normal nsp? Is it as simple as adding the required nca and cmnt files to another nsp?

**Comment by julesontheroad** [comment]
Yeah a nsp is like a tar file, as long as the installer can install what it's inisde. Traditionally goldleaf and old tinfoil did stop scanning nsps after they found the first cnmt  so they would only install the first content they found, then blawar's tinfoil, rommenu from SX OS and DBI install multicontent fine with or without tickets, i imagine the same goes for Awoo Installer since i think it was based on the fixed version of tinfoil.

**Comment by Masamune3210** [comment]
Alright, thanks! Awoo works fine, as that's what I use. Just needed documentation to explain to another dev what multicontent nsp files were exactly

**Comment by julesontheroad** [comment]
If he needs to read the version id and number quickly he can parse my tags. Basically NSCB follow some rules:
Name [titleid] [version number] (nG+nU+nD).nsp or .xci.
nG is number of Games
nU is number of Updates
nD is number of DLCs
Version number is the higher content number associated to the baseid
Titleid is the base id of the main content.
If several games are in the file the main content is the first one this is decided with the first baseid found. I don't add multiple id tags because of lengths since xci can have till 8 baseid and nsp multiple baseids in one file.
BaseID is the program id calculated from program, update or dlc.

Here you can see the concept of name parsing in the xcis listed. Squirrel uses it in some functions not included in NSCB and you can find the way to use it in ztools/lib/listmanager.py -> parsetags
![xci](https://user-images.githubusercontent.com/42461174/86125595-394b5b00-badd-11ea-8620-4442854897c9.PNG)

**Comment by Masamune3210** [comment]
Thanks! Sent them a link to the issue, the program is for scanning a folder of nsp files and spitting out any missing dlc or updates

**Comment by julesontheroad** [comment]
For dlcs normally my approach is if the update version matches i check the number of dlcs available, if that matches i give them as updated. The reason for this is that newer dlc versions always come with a new update, of course you can do a deepcheck over the content of the file but when some have more than 100 dlcs (taiko i'm looking at you) is non performance wise.
