### ISSUE TITLE
Save dumping errors out for games with special chars in title

### ISSUE THREAD

**Issue by Masamune3210** [julesontheroad/NSC_BUILDER#143]
Tried to dump all my saves, got a empty folder with the name of the first game, I'm assuming because it happened to be Cave Story +, which tripped something up as the script stated that it couldn't find the folder 

![image](https://user-images.githubusercontent.com/1053504/86867411-65944800-c098-11ea-9002-d05bfa0f16e2.png)

**Comment by julesontheroad** [comment]
Ah ok, i'm removing certain characters because i had that issue with **:** seems it wasn't enough, i'll check what to do to fix it.

**Comment by julesontheroad** [comment]
I think it wasn't the character. There was a bug when you don't add [titleid][version] to the zips, that's the default.
https://github.com/julesontheroad/NSC_BUILDER/pull/148/commits/d3d774e53e9ac4f153cd315ce870dcf0b7ca5c30

The one that works before is probably because it was in the csv of games that are currently installed registered. In this case the name was declared in the condition that triggers if you add titleid and version to the zip but not in the other case that is the default.

**Comment by Masamune3210** [comment]
Another glitch that I ran into involving that is I actually tried to change to add the title is but it would be set to false no matter what. I had to manually change it to true in the config file

**Comment by julesontheroad** [comment]
ah not exactly, that's intended to some degree. I should add that to the readme.

The explanation is the following DBI serves you the registries with titleid, you get all the installed games, archived and xci placeholders with versions of games, updates and dlc but for saves it gives you the saves decrypted in folders that have the game name.

If you select titleid+version i try to match the name in the save with the names in that registry. This has 2 downsides:
1.- You can't add this way titleid + version to games not currently installed, archived or with a xci placeholder. So if you delete the game you won't get titleid and version in the zip.
2.- If you have the same game installed from 2 regions and both have actually a save they will have the same name and can actually be asigned the same id if only one keeps installed. I think that would be a rare event and since the saves are decrypted they should be in most cases compatible between regions and even with pc, for example.

**Comment by Masamune3210** [comment]
Ok I'll switch it back and see if dumping works when I get home

**Comment by Masamune3210** [comment]
Tried dumping again and it worked fine!
