### ISSUE TITLE
Issue mergin Mario rabbids

### ISSUE THREAD

**Issue by Kyosfonica** [julesontheroad/NSC_BUILDER#15]
Hello,

I am trying to merge mario + rabbits base game + last update + dlc's into XCI. If I check the resulting file on XCI explorer I can see the last uptade applied but on the switch, the game is detected as version 1.8.5 that is the previous update, instead of 1.9.5. This causes the console to require the last update in order to launch the game.

If I install the nsp independently the game works fine installing those files.

This issue is happening on both 0.8.0 beta and previous version 0.7.9.

Is there anything I am doing wrong?

Regards

**Comment by julesontheroad** [comment]
Did you add the old update previously to the xci? If so you need to clean it with "Mode 4: Update mode"
You can also check what content and ids are inside the xci with the info function 1. Try checking that and see if you have several updates inside.
Lastly if your update was installed in your system previously try archiving the game before loading the xci.

**Comment by Kyosfonica** [comment]
Nope. Just last update file + base game + dlcs.
Using the info function I can see only one update - Build number: 1.9.589692 - The one that I'm adding to the bundle but the console detects the previous one.

I have installed the game to check the files and see that works. After that I deleted the game from the console and when loading the xci the game info displays the previous update instead of the one displayed on the info file.

**Comment by julesontheroad** [comment]
Are you sure you erased all content in the console related to that game? Also rabbids dlc have versions, it may be asking you for an updated dlc instead of an update. The full xci should match with the attached data:
Realize that the dlc have the following version numbers: 
010067300059b001 [v0]
010067300059b002 [v0]
010067300059b003 [v65536]
010067300059b004 [v131072]
Update:
010067300059a800[v589824]
[Mario Plus Rabbids Kingdom Battle + (v1.9.5 v589824 UPD) + (ALL DLC)-content.txt](https://github.com/julesontheroad/NSC_BUILDER/files/2809056/Mario.Plus.Rabbids.Kingdom.Battle.%2B.v1.9.5.v589824.UPD.%2B.ALL.DLC.-content.txt)

**Comment by Kyosfonica** [comment]
I do not know how but now it is working. I tried to build the xci with my nsp files but the launcher didn't recognized my game. Then I redownloaded the game from internet and now it works fine even though it was failing and that is why I tried to build it myself

Thanks.

**Comment by julesontheroad** [comment]
No idea. I plan to add a signature on the header that is unique for xci that incorporate the same files so we can check if the xci is correct, though I still didn't get to that.
