### ISSUE TITLE
permission error 

### ISSUE THREAD

**Issue by spling-du-futur** [julesontheroad/NSC_BUILDER#158]
when i try to use individual mode and upload files i get 
Exception: [Errno 13] Permission denied: 'C:\\Users\\Gnelon\\Downloads\\NSB_097x64\\list.txt'
why ???
and a screenshot : 
![screen](https://i.imgur.com/7X4vLCGl.png)

**Comment by spling-du-futur** [comment]
i use SX OS 3.0.3, sysnand fw 9.2.0 and emunand 10.0.4

**Comment by julesontheroad** [comment]
That seems like the program can't get permission to write the list in that path. Maybe try opening with admin rights or changing it's location.

**Comment by spling-du-futur** [comment]
nothing works

**Comment by julesontheroad** [comment]
After putting my glasses I think I see a 2 there which is the selector using the windows browser.
Did you try adding them by using drag and drop? Basically dragging a file or a folder in the window, input enter. Then dragging other file or other folder, input enter, ...
I don't know if there'll be any change since it seems permission related but is worth to try.

**Comment by spling-du-futur** [comment]
SOLVED :)
i close issue
