### ISSUE TITLE
add latest available update/dlc support

### ISSUE THREAD

**Issue by mspykerez** [julesontheroad/NSC_BUILDER#178]
Is it possible to add support for listing the latest updates/DLCs for a given games ?
Hopefully based on this: https://github.com/blawar/titledb

**Comment by julesontheroad** [comment]
For local you mean? It is planned the open issue from here:
https://github.com/julesontheroad/NSC_BUILDER/issues/114
For mtp is already added. In device info you have an option that shows new updates and dlcs for installed games based on the versions DB from blawar.
There's also the autoupdate function that checks against your Google drive or local libraries.
Closing this since it's being talked in the other thread.
