### ISSUE TITLE
Friends I got a error on choose option 2 multi-pack option

### ISSUE THREAD

**Issue by cobr4a** [julesontheroad/NSC_BUILDER#189]
I´m using v98b version early and not get error and continue working well.
Any newers versions this error happens:

  File "lib\nutdb.py", line 626
    csvfile.write(f"{i}|{ver_txt_dict[i]}\n")
                                           ^
SyntaxError: invalid syntax
WHAT DO YOU WANT TO DO?

And program repeat and repeat this error.

Anyone get this problem?

**Comment by julesontheroad** [comment]
Ah ok you're using the python version. Your python is probably older than 3.6 and doesn't support f strings.
Since most people used the exes i started using f strings heavily since they are nicer than .format()
https://realpython.com/python-f-strings/

They were introduced on python 3.6 and i'm using it heavily on the mtp mode and other new functions. That function was added to nutdb on 1.0 and consolidate the versions between the versions.txt and versions.json.

**If you upgrade your python to 3.6, 3.7 or 3.8 or start using the exes it will work for you. Currently my testing environments are python 3.7 and python  3.8.**
