### ISSUE TITLE
fails to import modules

### ISSUE THREAD

**Issue by tuxinal** [julesontheroad/NSC_BUILDER#190]
i am getting an error when i try to run this program on linux using this command ` sudo python3 squirrel.py -lib_call Interface start`
this is the error : 
`Traceback (most recent call last):
  File "squirrel.py", line 43, in <module>
    import sq_tools
  File "lib/sq_tools.py", line 3, in <module>
    import Hex
  File "lib/Hex.py", line 2, in <module>
    import Print
  File "lib/Print.py", line 1, in <module>
    import Status
  File "lib/Status.py", line 1, in <module>
    import tqdm
ModuleNotFoundError: No module named 'tqdm'
`
i downloaded `NSCB_100dpy.zip` from the release page and i am running the command from the ztools directory,
have i done something wrong?

**Comment by julesontheroad** [comment]
You need to have tqdm installed for it to import:
```
python -m pip  install --upgrade pip
python -m pip  install wheel
python -m pip install urllib3 unidecode tqdm bs4 tqdm requests image pycryptodome pykakasi googletrans chardet bottle zstandard colorama google-auth-httplib2 google-auth-oauthlib oauth2client 
python -m pip  install --upgrade  google-api-python-client
```
That kinda covers everything the program could be able to do on linux since the rest are windows dependencies. 

For interface it will also need a python distribution built with tkinter support.
`sudo apt-get install python3-tk`
or to build python manually with tkinter.

**Comment by tuxinal** [comment]
ok now it runs but i remember it having some sort of nsp to xci thing how do i do that from the interface? is that in the batch file?

**Comment by julesontheroad** [comment]
That isn't on the interface i'd probably add it on the future but currently the interface purpose is file information. 
On linux is intended for to use with the command line or with shell scripts though is not officially supported since i don't use it enough to give support for it, i only use some custom make scripts on my headless server.

**Comment by tuxinal** [comment]
is there any command i can run with the squirrel.py file to do that? or any other file?

**Comment by tuxinal** [comment]
i noticed the squirrel.py file takes some arguments

**Comment by tuxinal** [comment]
for anyone else who wants to use this in linux you need to install python in wine then run install_dependencies.bat using wine and THEN open the NSCB.exe and enter your file locations manually when prompted,

**Comment by tuxinal** [comment]
you can also make a file called list.txt in the same folder as NSCB.exe and put your file addresses there keep in mind they should be in windows format so replace forward slashes with back slashes also it needs a drive letter which in wine the linux root drive letter is Z:\ by default so /home/user/game/game.nsp would be Z:\home\ebi\game\game.nsp
