### ISSUE TITLE
Request for a option to disable NUTDB auto update feature

### ISSUE THREAD

**Issue by CaiMiao** [julesontheroad/NSC_BUILDER#191]
I just don't want to update this thing, because the NUTDB is useless to me, plus sometimes it auto updates without my permission when I'm going to select some file to convert and it just hangs me for few meanless minutes. I'm really pissed at such circumstance.

Consider one have a limited or slow Internet environment, the update can be long and have no asynchronous ability.

**Comment by julesontheroad** [comment]
Is set to autoupdate by default every 24h, each db checks if the spam of time passed when squirrel needs to check the db for something the titles db is also checked when the nutdb module is called.
You at least need nutdb to name dlcs since they don't have nacp file which contains the content name. If the dlcs are not in the db it will default to use the dlc number as name. There's also more things linked to some of the databases like the xci firmware checker.

The nutdb can be disabled by using it's configuration:
In zconfig:
NUT_DB_URL.txt
NUT_DB_REGIONS_URL.txt

No need to update mirrors since they won't get checked.

NAME|URL|REFRESH(h)|REFRESH(m)|REFRESH(s)
TITLES|https://raw.githubusercontent.com/blawar/titledb/master/titles.US.en.json|24|0|0

Just replace in each entry 24h for a high number like 99999999999999999999999.

I distributed for a longtime an offline db with the config files set up but i determined it was a niche thing.

Anyway here's the configuration for offline DB + current DB files. Just decompress and merge the zconfig inside with your zconfig in the NSCB folder:

[NUTDB_no_autoupdate.zip](https://github.com/julesontheroad/NSC_BUILDER/files/5048271/NUTDB_no_autoupdate.zip)

I guess i can add an option in the configuration that sets the time to the databases globally though they were meant to set up on a per database basis.

No autoupdate files will be added also to current release.

**Comment by CaiMiao** [comment]
I agree that NUTDB still have some sort of use but I just don't want to update it everytime I'm going to use it.
The 24h interval actually does not make much sense - at least for a average use like me, will not use this thing **everyday**.
I'm looking forward for an actual option to disable auto update, or more possibly, ask before update.

**Comment by julesontheroad** [comment]
i mean for now download those files and it'll be set to a spam of 999999999999999999999999999999999999999 hours. Also every time you force a nutdb update with the option in the configuration it'll refresh the update interval.
