### ISSUE TITLE
What's "Skipping delta fragment" in compress NSP to NSZ

### ISSUE THREAD

**Issue by WanderMax** [julesontheroad/NSC_BUILDER#192]
When I compress NSP  to NSZ, it shows "Skipping delta fragment"  in  terminal window.
Is there anything wrong for this message?
Thanks
![image](https://user-images.githubusercontent.com/15909056/90022644-5b8fe580-dce5-11ea-8fe9-fee7f73dc691.png)

**Comment by Masamune3210** [comment]
delta fragments are basically parts of the update that can be used to patch already existing updates, so you don't end up with two copies of the update installed. most tools get rid of them because they are pretty much useless unless you are using the eShop

**Comment by WanderMax** [comment]
thanks, I will ignore this message later.

**Comment by julesontheroad** [comment]
Yep that's it, also the only installer that can make use of them is devmenu, the others will ignore them.
Other thing to note is scene groups will add all version fragments, so if you are in update 8:
- You have fragments that convert update 1 to 8, update 2 to 8, update 3 to 8... They can double an update file size's sometimes.
They are useful for Nintendo since when a user has update X eshop will only download the fragments to convert it to the last update, which saves time. Is not that useful for cfw users.

- Anyway if you want to keep them there's an option in configuration called **DELTA files treatment** that option applies to the compressor, though they won't get compressed since compression of delta fragments isn't implemented. I think it can be implemented but it would deviate from the standard.
