### ISSUE TITLE
TAB key don fill folder structure

### ISSUE THREAD

**Issue by pmferraro** [julesontheroad/NSC_BUILDER#20]
hi, when i press TAB key to fill location to file don work

**Comment by julesontheroad** [comment]
I don't understand you, you add files by dragging a folder (it detects files inside the folder and subfolder) or by dragging files 1 by one. Once you dragg one you press enter and then you can dragg other one.

**Comment by pmferraro** [comment]
Hi, sorry for my english:
in upgrade mode for example, when the script ask to type the path of the upgrade folder, before (Ver 0.80) pressing the TAB key the path was automatically completed, now it does not. 
If I complete it when I have to write the base game path. THE TAB key works fine in Base GAme path

**Comment by julesontheroad** [comment]
Yeah there is a reason for that, the latest beta uses the python console to get the input to fix the issues the program had with special characters, it'll also allow special functions, that are not enabled yet, in the future like filtering lists by certain conditions.
I guess python rawinput is not compatible with autocomplete.
The base game is still process by cmd, that's why it works there. It was never ment for you to type the paths but for you to dragg folders or files.
Either way looking at google i see there are several approaches i can take for the people that don't like to dragg the files, i may look into that in the future.

**Comment by julesontheroad** [comment]
Well i added an option in 0.95 to select folders and files via the tkinter filebrowser. I still plan to add the search one and a filter system for the list. This should make it a little easier if you can't dragg the files.

**Comment by julesontheroad** [comment]
The python console keeps it's own history so this can't be fixed easily. Closing for now.
