### ISSUE TITLE
squirrel.exe detected as a trojan by Windows antivirus

### ISSUE THREAD

**Issue by shadow2560** [julesontheroad/NSC_BUILDER#206]
The version 1.01b X86 (not tested with X64 version) is detected as a "Trojan:Win32/Wacatac.C!ml" by Windows Security Essential. The problem wasn't present on 1.01 version.

**Comment by julesontheroad** [comment]
only relevant change i did on x86 was update python on my virtual machine and reinstall the library dependencies.
I had an error where it said python.exe got corrupted so i updated from Python 3.8.5 to Python 3.8.6, i saw there's 3.9 but need to test first on my python environment. Then i updated all the python libraries.
I didn't make any other changes.
When checking with virustotal it seems to give me that warning from Microsoft in the x86 too, maybe that's related to the issues in the VN. I'll take it out for now and remake that machine.
X64 isn't showing those warnings and is made with other virtual machine, i use 2 VM with windows 7 for compatibility to make the builds since windows 10 doesn't include the dlls 7,XP and vista need.

**Comment by julesontheroad** [comment]
The issue is within the new version of pyinstaller. Since i updated python on the x86 VM i also updated pyinstaller. I ended setting up a build on Windows Sandbox which ended with the same issue.
Upon investigation i realized current pyinstaller build has that false positive. For more information:
https://github.com/pyinstaller/pyinstaller/issues/4633

**Comment by julesontheroad** [comment]
So i built the boodloader myself as specified in stackoverflow, so the signature is different, and the false positive persist. For whatever the reason something in newer pyinstaller binaries raises those false positives.

**Comment by julesontheroad** [comment]
Best that can be done is to reduce the virus total engine warnings with the bootloader in-system compilation from 8 to 6 without downgrading pyinstaller.
http://www.mediafire.com/file/cvdwa1y7blsn0q9/squirrel.zip/file

**Comment by shadow2560** [comment]
Thanks, this seems to work (quick test only with a game repack) and no antivirus warning. A good idea could be to include the spec file that you use to pack Squirrel with Pyinstaller on your project repository, this could help to pack by ourselves the project if we want.
