### ISSUE TITLE
CNMT XML file format - KeyGenerationMin

### ISSUE THREAD

**Issue by alguiennadie** [julesontheroad/NSC_BUILDER#27]
https://github.com/julesontheroad/NSC_BUILDER/blob/ca10e882d7c1977186b30e7fc4ee18e4e23c8f7f/py/ztools/Fs/Nca.py#L826

When converting a NSP to NSP a new CNMT XML is generated by NSC_Builder. The new file is different in file format from the original one. The tag "KeyGenerationMin" near the end of the original file has been renamed to "KeyGeneration" in the new file. This causes some NSP verification software to be unable to recognize the NSP. Note, the tag inside ```<Content>``` should be  ``` <KeyGeneration>``` and is correct in both files.

Original CNMT XML:
```
<ContentMeta>
...
<KeyGenerationMin>...</KeyGenerationMin>
<RequiredSystemVersion>...</RequiredSystemVersion>
...
</ContentMeta>
```
---

NSC_Builder Generated CNMT XML:
```
<ContentMeta>
...
<KeyGeneration>...</KeyGeneration>
<RequiredSystemVersion>...</RequiredSystemVersion>
...
</ContentMeta>
```

*Code in two places in Nca.py (Lines: 826 and 952), first occurence shown in issue.

**Comment by julesontheroad** [comment]
I use nut's format which is exactly the same one all community dumps use. I could check what the sdk uses but to be honest the tendency is to get rid of xmls since they're not a cdn format, and all the information the xmls have is included already in the ncas. I'll keep giving support to it for a while but if nut removes it too i'll probably do the same definitely.

**Comment by alguiennadie** [comment]
CDNSP.py from nut uses "KeyGenerationMin" as well, Line 675
https://github.com/blawar/nut/blob/d6ee16b0cdbf3a8d74dd9d8ed49a1b9cf6d9ffea/CDNSP.py

4NXCI also uses "KeyGenerationMin" when generating the CNMT xml file during XCI to NSP conversion.

**Comment by julesontheroad** [comment]
That changed at some point then because i used CDNSP as reference. Dunno when it was corrected but i checked a couple of files before my first answer and they still had keygeneration in the last line. I know checked the more recent ones i had and you're right they say _KeyGenerationMin_
I'll correct it since it seems to be the proper standard though i don't understand why any program would read information from the xml instead of reading it directly from the nca files.

**Comment by julesontheroad** [comment]
This was changed already
