### ISSUE TITLE
SyntaxError: Non-UTF-8 code in Squirrel.exe

### ISSUE THREAD

**Issue by iiLaurens** [julesontheroad/NSC_BUILDER#34]
When running the main program (for example browsing the menu or trying to pack a XCI in legacy mode) I get the following error:

```
  File "D:\switch\NSCB\ztools\squirrel.exe", line 1
SyntaxError: Non-UTF-8 code starting with '\x90' in file D:\switch\NSCB\ztools\squirrel.exe on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

Do you know what might cause this? I'm using a fresh Python 3.7 install (Anaconda based) on Windows 10.

**Comment by julesontheroad** [comment]
From releases or from the master? This error popped out before and it was due to github corrupting the downloads from the master. Python is irrelevant on the exe versions even if it's referenced.
I started zipping them on the master for that reason since it seems it protects them a little.
Just in case, new versions (0.83b) uploaded on mediafire:
https://www.mediafire.com/file/m9rsziyjt7gwrf1/py.zip/file
https://www.mediafire.com/file/spt5v47rt2b1lpu/x86.zip/file
https://www.mediafire.com/file/cav85u6orfg8s94/x64.zip/file
Also the python version should work for you. If you use anaconda edit in the NSCB_options.cmd file in zconfig **set "pycommand=py -3" for set "pycommand=conda -3" or set "pycommand=conda"**
