### ISSUE TITLE
Error in 0.86c with Multi-pack

### ISSUE THREAD

**Issue by RichyH72** [julesontheroad/NSC_BUILDER#50]
Hi Jules,
First thanks for this great tool. Took some investigating but I got it to work,
I was using 0.85 without problems and tried the 0.86 today.
When selecting option "Input "2" to enter into MULTI-PACK mode" I do not get the line to add files and folders but the following:

*******************************************************
Processing list
*******************************************************
Traceback (most recent call last):
  File "D:\NSCB\ztools\squirrel.py", line 2973, in <module>
    with open(tfile,"r+", encoding='utf8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '\\%f'
Cannot access file D:\NSCB\mlist.txt
...................................................
STILL 0 FILES TO PROCESS
...................................................
---------------------------------------------------
*********** ALL FILES WERE PROCESSED! *************
---------------------------------------------------

When reverting back to 0.85 I do not have any issues.
I ran install_dependencies.bat to make sure everything is up-to-date.

Maybe an error on my side.
This is the fist version I retrieve from the PY folder as there is no x64.zip file available.

Cheers,

Richard

**Comment by julesontheroad** [comment]
ah, that's probably github corruption on files we already had that issue before when downloading from the master, if doesn't happen if you clone the repo from the app normally. That was the reason i started putting the zips for x64 and x86. Since i moved active coding to beta i deleted the x64 and x86 to make merges easier.
BTW the code in master is exactly the same as in release so you can use the releases without and be up to date. Please test them and tell me if you have the same issue
https://github.com/julesontheroad/NSC_BUILDER/releases/tag/v0.86c
Here are the latest released files:
[NSB_086c_py.zip](https://github.com/julesontheroad/NSC_BUILDER/files/3263824/NSB_086c_py.zip)
[NSB_086c_x64.zip](https://github.com/julesontheroad/NSC_BUILDER/files/3263825/NSB_086c_x64.zip)
[NSB_086c_x86.zip](https://github.com/julesontheroad/NSC_BUILDER/files/3263826/NSB_086c_x86.zip)

**Comment by RichyH72** [comment]
I've tested the x64 and it was working again :)
Only thing I still cannot get to work is drag and drop.
In the past I used the TAB to complete, that is no longer supported.
Now I just copy and paste the file location.
When using D&D in the 0.86c I get this error:

PLEASE DRAG A FILE OR FOLDER OVER THE WINDOW AND PRESS ENTER:
Traceback (most recent call last):
  File "squirrel.py", line 4349, in <module>
IndexError: string index out of range
[11484] Failed to execute script squirrel
="=="0" goto manual_Reentry was unexpected at this time.

**Comment by julesontheroad** [comment]
Hmm, i'll try to check what i have on that line. The difference is that i need pytho to parce the input so it recognize all characters.
Either way I'll add soon the option to add library folders and search trough them to add the files. Like input a name or a titleid to find the files in the folders you added.

**Comment by RichyH72** [comment]
Those sound like some nice options.
Looking forward to seeing them implemented.
