### ISSUE TITLE
File joiner mode does nothing

### ISSUE THREAD

**Issue by sjug** [julesontheroad/NSC_BUILDER#64]
1. Press `7` to start file joiner mode
2. Drag and drop directory containing files to join and press enter
3. Press `i` to see list of files to process
4. We now see the main menu rather than the files we just added

Alternatively you can try to process by selecting 1, but after going through the flow it immediately says all files were processed when none of them were and there is no file output.

**Comment by julesontheroad** [comment]
You're right about the "i" not working properly but i just downloaded the release and the mode itself is doing what was intended, if processed it takes the xc0, ns0 or 00 files and associated them with the xc*,ns*,0* files under the same name on it's same directory and joins them in the output folder. Not sure if you're trying to join other kind of extension, the list only adds those 3 since is meant to join fat32 files, it basically gets it's own mode because of those extensions.

**Comment by sjug** [comment]
Thanks @julesontheroad, I was trying to merge nsp files.

**Comment by julesontheroad** [comment]
Fixed
