### ISSUE TITLE
Problem converting certain new games

### ISSUE THREAD

**Issue by AizenSousuke** [julesontheroad/NSC_BUILDER#71]
![screenshot 2019-09-17 20 20 02](https://user-images.githubusercontent.com/652686/65041260-f58dc780-d988-11e9-8d2c-8d0bdd172aa8.png)

As shown in the attachment, the first file always screw up in its file size causing the whole batch to fail when trying to run it in the switch. 

Attached settings:
[NSCB_options.zip](https://github.com/julesontheroad/NSC_BUILDER/files/3621220/NSCB_options.zip)

**Comment by julesontheroad** [comment]
Yeah is the same issue as #70 I have yet to check what's the problem.

**Comment by julesontheroad** [comment]
Couldn't fixed it currently for mode 2 due to the way it works, any file has a chance of being a little smaller. Anyway i checked it myself and the files work since xc0 and ns0 allow any split size, i think the issue is that xci was either the file needed a bigger masterkey than what you had or i fixed it when i fixed the other fat32 issue even if the block size is still non consistent.
