### ISSUE TITLE
White icon for new games

### ISSUE THREAD

**Issue by RichyH72** [julesontheroad/NSC_BUILDER#79]
When coverting a new game + update using 0.94b to xci the icon is white in SXOS.
Went back to 0.91 and no problems.
SXOS: 2.9.2
Switch 9.01
Game Ice Age Scrats Nutty Adventure

**Comment by julesontheroad** [comment]
That's an sx os issue probably. The update from that game uses the masterkey_09, their loader\installer seems to have the keys embedded either in the nro or the boot.dat and is not the first time they forgot to either add the new keys or give access to the installer to those keys. If you change keygeneration to a lower one it'll show the icon, keygeneration 8 is a sure bet, keygeneration 9 may have the same issue since i don't remember masterkey 08 ever being used, so is possible they forgot to add that one too.

**Comment by RichyH72** [comment]
Thanks for the explanation.
Is changing the key something I can do?
Is that just patching the game to a lower version?
I can drop a message on their board and see what they have to say.
Strangly enough the icon only stays white in the over list (Album) and not on the main screen,

**Comment by julesontheroad** [comment]
Yes, basically if you choose to patch the RSV it asks you if you want to set a maximun keygeneration. If you set it to keygeneration8 that means the files can be decrypted with masterkey7 which was present in FW7.0-8.01 and i know for sure their loader can decrypt.
About the icon only being white in the album that's normal. Their loader decrypts the contro nca file to show the icon, once they call the mounting process the system register the meta and control nca by itself. Basically the system is handling the decryption of the ncas once mounted.
If this is anything like 6.2 where the issue also happened the installer\loader from the gallery, which they call rommenu, won't be able to install those files that uses masterkey9 (keygeneration 10). So things like the  Ice Age Scrats Nutty Adventure will probably fail with rommenu but be able to install with tinfoil\sx installer, tht was what happened in 6.2 till they updated the installer properly.
I think it was 6.2 at least. there were several messages on my gbatemp thread from when we investigated the issue on it's day.

**Comment by julesontheroad** [comment]
Solved by Xecuter a while back
