### ISSUE TITLE
Many missing game versions (revisions)

### ISSUE THREAD

**Issue by Stuntaneous** [julesontheroad/NSC_BUILDER#80]
Is this something I can fix or missing information in a data source NSC_B accesses?

**Comment by julesontheroad** [comment]
If you mean the web interface it tries to read all the information possible infile. It uses support from the nutdb\tinfoil.io for dlc namings, pictures and description from nintendo.com, release dates,...
Basically all that is eShop information and dlc names since these can't be read from file.
If the data is not there it means it didn't hit the eShop. If you're using the separate zip as DB the configuration files are setup to update once every 999 days, you force the update in the configuration, is meant for offline users.
If you don't use that zip the program tries to download the DB files each 24 but you can change that with the files placed in zconfig. If the download errors out or the request sends back a 404 message it keeps the old files.
There will be a DB mode that's based in a custom format that has faster read access and will include all the data the GUI shows but it isn't finished yet.
Either way I could add an option to setup missing information via a user json or something similar.

**Comment by Stuntaneous** [comment]
I mean the "game revision" column in the "eShop files" tab. A very small proportion of games have a version number. I notice XCI Explorer is able to retrieve the numbers for everything thrown at it - would you be able to replicate that functionality? 

Sorry for the less than comprehensive response, I'm incredibly tired but wanted to shoot you a response regardless today to move things along.

**Comment by Stuntaneous** [comment]
In my extreme tiredness I've managed to bug you about something meant for another repo. Very sorry.

**Comment by julesontheroad** [comment]
Don't worry about it ;)
