### ISSUE TITLE
Ignore Framework RequiredSystemVersion 

### ISSUE THREAD

**Issue by michelveloso** [julesontheroad/NSC_BUILDER#9]
Hi, 

I don't know if is possible, but is there a way to ignore framework system version like Tinfoil does?

Regards

**Comment by jlozes** [comment]
The problem is that this not seems to work correctly because if the option "patchRSV" is set to "true", the generated files are corrupted when you try to launch them on the Switch. If the option is set to "false", the files work without problem. I think there is a problem with this option, I haven't start to investigate on it but I think it's better to report the issue to you even if I don't have a clue for how to fix it.

**Comment by julesontheroad** [comment]
It works fine for me in SX OS and ReiNX. It's meant for xci primordialy even if it can work with nsp. 
There isn't any problem with the option, it works as it's meant to.

**Comment by julesontheroad** [comment]
It basically change the requiredsystemversion in the cnmt.nca and rebuilds the internal hashes, then lastly it changes the nca name to match it's hash.

**Comment by julesontheroad** [comment]
Ok, to identify your issue, tell me:
1.- To what are you repacking (nsp or xci)
2.- What games, updates or dlc are you repacking.
3.- What CFW are you using.
4.- In what firmware version are you in. (Very important)
5.- What are you using to install incase it's a nsp.
6.- Exact error you are getting.

**Comment by jlozes** [comment]
I've tested it with SX OS 2.3 Beta, on firmware 6.1.0, it's a multi repack from NSPs to XCI, with the game Minecraft. I will test it with a NSP repack and also with single repack to see if the problem is the same or not. At least, I can say that if I disable the ignore update function, the game and update repacked work without any problem.

The error occure when the XCI is mounted and say that the card can't be red and to take out the card and put it back into the Switch. I haven't the exact message because my console is in french language but it's the aproximate translation of the first lines of the error message.

**Comment by julesontheroad** [comment]
I can assure you the function works with game+update with the things I tried like:
- Steven Universe (game + update)
- Pianista (game + update)
- Civilization VI (game + update)
On all these the game would ask to update to 6.0-6.1 when repacked with the update and it's no longer the case.
Then you have Bendy and the Ink Machine, for this one you'll need to update since the update uses keygeneration 6 wich refers to FW 6.0-6.1 even if you do the patch. If you don't update it'll give the error you are referring to, but that is because your console **lacks the key to decrypt the update.** if you're in 5.1, and of course it won't ask ou to update since the restriction is removed.
Now what I can do to avoid confussion is to do some digging into the RequiredSystemVersion numbers and set that one up to the range equivalent to the keygeneration. Just posted this explanation in gbatemp:
We have 2 restrictions:
1.- RequiredSystemVersion: This one can be false if it's bigger than the range of firmawares in the keygeneration used.
2.- keygeneration: It's the cryptography used to encrypt the nca body. If it's bigger than your firmware the nca content won't be able to get decrypted. So keygeneration=5 (FW 5.X); keygeneration 6 (FW 6.0-6.1), keygeneration 7 (FW 6.2)

Now, why is this important?. I'm patching the meta to a fixed value currently (this is because the system version number is not straight forward so to know the range for each keygeneration I'll need to do some investigation) so when patch the xci will try to load but if it requires a bigger crypto it'll give cartridge error.
This is the case of Bendy and the Ink Machine. If you repack it with the update it'll give the error in 5.1 but work in 6.0-6.1, this is because the crypto used is the one from 6.0-6.1 (keygeneration 6)
So I'll try to do some digging and set that to the exact range for each keygeneration but this is so you now that when it fails you better check the real requirements for the update since you just may need to update. As happens when it fails with tinfoil.

**Comment by julesontheroad** [comment]
Now for Minecraft this is a different issue not related to the meta patch. It seems that titlerights are not correctly remove for this one as it happens with some Xenoblade 2 DLCS. **I'll investigate and open a new issue related to the actual problem.**

**Comment by julesontheroad** [comment]
Opened this one about this https://github.com/julesontheroad/NSC_BUILDER/issues/11
It's really weird actually. Basically if you don't patch the update it works for this one and if you patch the update but install it with SX installer as nsp it also works, it seems to not work as xci. I repacked a xci with only the update with the same issue (yes you can use xci with only update if you have the base game installed).
The base game has keygeneration 0 and a RSV set as 0 so I tried patching the update to that with the same result, also tried patching it to another value with the same result. Then I tried games with the  RSV set as 0 but they worked.
I also looked at the multi-minecraft with xci builder and it doesn't read it properly so I think for some reason the changed nca is making hacbuild work unproperly for this game in particular but I don't understand why since according to my experience if the nsp works the xci works (till now)

**Comment by julesontheroad** [comment]
I think the best solution will be to ask if you want to patch the meta before the program starts processing the files. That way the average user will understand that in the case the xci fails it sould be related to that.
I may set a note like tinfoil does even.

**Comment by julesontheroad** [comment]
Completely solved in current master of the program
