### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by Official-MadoX** [julesontheroad/NSC_BUILDER#90]
![image](https://user-images.githubusercontent.com/39462203/69001297-a0473700-08a1-11ea-9033-21ab76bf8bfc.png)
this happened when I pressed 1 as the .bat opened

**Comment by julesontheroad** [comment]
Well here it seems you're using the python version in first place. Dunno if your config matches that, anyway that error is due to not have the requirements installed or because you're using python2 to execute the script, is exactly the first error you get when you are using python2 instead of python3.
