### ISSUE TITLE
Error running python script in Ubuntu

### ISSUE THREAD

**Issue by lamazze** [julesontheroad/NSC_BUILDER#91]
Hello,

Sorry if my question is stupid but I've never used python before.

I've installed the required packaged: urllib3 unidecode tqdm bs4 tqdm requests image pycryptodome pykakasi googletrans chardet eel bottle

I've downloaded eel from https://github.com/ChrisKnott/Eel and I've overwritten the files where eel was installed (python3.6/site-packages/eel).

I've tried to run the squirrel script like this: sudo python3 ./squirrel.py -lib_call Interface start

I had to install several more packages.

And now I'm getting this error and I'm stuck:

sudo python3 ./squirrel.py -lib_call Interface start
Exception: No module named 'gevent.__hub_local'

Anyone know what's the problem ?
Thank you!

lamazze

**Comment by julesontheroad** [comment]
Since to be asking you for gevent. It for gevent, I know that in linux when you compile python sometime you need to install more stuff for it to compile properly, dunno if that's the case but it seem it wants gevent.
pip install gevent. Also try to install the requirements with sudo, gevent may be one requirement of the other modules that didn't get installed properlly with sudo.
Finally i think they updated the eel in pypy and now it isn't necessary to overwrite the module by the master.
https://pypi.org/project/gevent/

**Comment by lamazze** [comment]
I've tried that but I still have the error.
I think my python installation is corrupted or something.
Unless you have another idea, I give up; I will use Windows instead.

**Comment by julesontheroad** [comment]
Only thing I can think off if you can't compile python by yourself is to use a prebuold binaries. I have the ones I use on Linux with squirrel and I don't mind sending them to you but I need to test if they work in other Linux machine.

**Comment by lamazze** [comment]
Yes why not, I will test it. thank you.
